name: cupcakesbr
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get_storage: ^2.0.3
  validatorless: ^1.2.3
  intl: ^0.17.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/



  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fonts/mplus1/MPLUS1p-Regular.ttf
          style: normal
        - asset: assets/fonts/mplus1/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/mplus1/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/mplus1/MPLUS1p-ExtraBold.ttf
          weight: 800
